### ISSUE TITLE
Not working on Kali 2021.1

### ISSUE THREAD

**Issue by Grezzo** [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a#4]
Sadly it's not working for me on Kali 2021.1:

```
$ pyrit
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key
```

**Comment by Grezzo** [comment]
In case it helps, [I created a script](https://github.com/Grezzo/pyrit-installer-for-kali-rolling/) which works for me. I had to edit the C source code before compilation to get it to work.

**Comment by hacker3983** [comment]
oh nice no problem good work man i will make it work for you.

**Comment by hacker3983** [comment]
oh nice i will make it better
